###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 09-04-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# path to the directory with all the scripts for this pipeline
# (relative to the 'execution' directory)
CSM_scripts_dir: "../scripts"

# path for the output directory
# (relative to the 'execution' directory)
CSM_outdir: "../3pUTR_kmers_3to7mers"

# path to the genomic sequence in fasta format
CSM_genomic_sequence: "/data/scc2/ag-gruber-ext/wsciekly.maciek/resources_ENSEMBL_hsa/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

# relative ranges around respective sites
CSM_regions_ranges:
  "polyA": "150-150"
  "3ss": "150-50"
  "5ss": "50-150"

# paths to the bed-formatted sites
CSM_regions_files:
  "polyA": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-precomputed-ase-tpa-csm/tpa_outdir_unstranded/tandem_pas.terminal_exons.representative_sites.bed"
  "3ss": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-precomputed-ase-tpa-csm/ase_outdir_minlen0/3ss.bed"
  "5ss": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-precomputed-ase-tpa-csm/ase_outdir_minlen0/5ss.bed"

# paths to the bed-formatted additional whole regions
CSM_additional_regions_files:
  "3pUTR_minlen150_prefix": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-stability-analysis/singular-sites-margin25-minutrlen150/clean-sites-prefix-UTR.bed"
  "3pUTR_minlen150_total": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-stability-analysis/singular-sites-margin25-minutrlen150/clean-sites-total-UTR.bed"
  "3pUTR_minlen150_suffix": "/data/scc2/ag-gruber-ext/wsciekly.maciek/mapp-stability-analysis/singular-sites-margin25-minutrlen150/clean-sites-suffix-UTR.bed"

# sliding window configuration: window size and slide step
CSM_window_size: "50"
CSM_window_step: "25"

# sitecount matrix type: "kmers" or "pwms" options available
CSM_matrix_type: "kmers"

# options for "kmers" sitecount matrices:
# inclusive ends specification for the range of k-mers sizes = [kmer_min,kmer_max]
CSM_kmer_min: "3"
CSM_kmer_max: "3"

# options for "pwms" sitecount matrices:
# path to the directory with TRANSFAC-formatted PWM files
CSM_pwm_directory: "/data/scc2/ag-gruber-ext/wsciekly.maciek/ATtRACT_hsa_clean/motifs"

# MotEvo parameter: prior probability for the background binding
CSM_MotEvo_bg_binding_prior: 0.99

# MotEvo parameter: prior minimum binding posterior probability
CSM_MotEvo_min_binding_posterior: 0.01

# MotEvo parameter: order of the Markov chain
CSM_MotEvo_Markov_chain_order: 1

...
