

KPC_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_KPC/config.yml modules/KAPAC/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/KAPAC/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

RES_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_RES/config.yml modules/REPORT_RESULTS/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/REPORT_RESULTS/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

...
