
PQA_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_PQA/config.yml modules/PREPROCESSING/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/PREPROCESSING/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

ASE_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_ASE/config.yml modules/EXTRACT_AS_EXONS/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/EXTRACT_AS_EXONS/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

TPA_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_TPA/config.yml modules/PREPARE_TANDEM_PAS/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/PREPARE_TANDEM_PAS/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

QEI_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_QEI/config.yml modules/QUANTIFICATION/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/QUANTIFICATION/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

PAQ_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_PAQ/config.yml modules/PAQR/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/PAQR/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

CSM_module:
  script:
    #
    # test1: kmers
    #
    # overwrite w/ the test config:
    - cp .test/integration/module_CSM/config1_kmers.yml modules/CREATE_SITECOUNT_MATRICES/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/CREATE_SITECOUNT_MATRICES/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8
    - cd /builds/zavolan_group/pipelines/mapp
    #
    # test2: pwms
    #
    # overwrite w/ the test config:
    - cp .test/integration/module_CSM/config2_pwms.yml modules/CREATE_SITECOUNT_MATRICES/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/CREATE_SITECOUNT_MATRICES/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8
    - cd /builds/zavolan_group/pipelines/mapp

MAE_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_MAE/config.yml modules/MAEI/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/MAEI/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

KPC_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_KPC/config.yml modules/KAPAC/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/KAPAC/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

RES_module:
  script:
    # overwrite w/ the test config:
    - cp .test/integration/module_RES/config.yml modules/REPORT_RESULTS/configs/config.yml
    # cd into module exec directory:
    - cd /builds/zavolan_group/pipelines/mapp/modules/REPORT_RESULTS/execution
    # snakemake DAG run (test script):
    - bash snakemake_dag_run.sh
    # snakemake dry run:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --printshellcmds
      --dryrun
      --verbose
    # build conda envs for the rules:
    - >
      snakemake
      --snakefile=../Snakefile
      --configfile=../configs/config.yml
      --use-conda
      --conda-create-envs-only
      --cores 8

...
