snakefile: "../Snakefile"
local-cores: 1
cores: 32
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: conda
keep-going: true
verbose: true
jobscript: sge-jobscript.sh
cluster: "sge-submit.py"
cluster-status: "sge-status.py"
latency-wait: 120
jobs: 32
