###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHORS: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 11-11-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# path to the directory with all the scripts for this pipeline
# (relative to the 'execution' directory)
MAE_scripts_dir: "/home/runner/work/MAPP/MAPP/modules/MAEI/scripts"

# path for the output directory
# (relative to the 'execution' directory)
MAE_outdir: "/home/runner/work/MAPP/MAPP/modules/MAEI/output"

# path to the quantified per-exon summed-up transcript expression information
# (as in the output of QEI module)
MAE_inclusion_table: "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/inclusion_table.tsv"

# TSV-formatted design table with information regarding RNA-Seq samples (quality-filtered set)
MAE_design_file: "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/design_table.tsv"

# per-region, per-window paths to the sitecount matrices
MAE_sitecount_matrices:
  "3ss":
    "u0to0.d0to50": "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/3ss/u0to0.d0to50/matrix.tsv"
    "u50to0.d0to0": "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/3ss/u50to0.d0to0/matrix.tsv"
  "5ss":
    "u0to0.d0to50": "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/5ss/u0to0.d0to50/matrix.tsv"
    "u50to0.d0to0": "/home/runner/work/MAPP/MAPP/.test/integration/module_MAE/5ss/u50to0.d0to0/matrix.tsv"

# minimal fraction of sequences which must contain a binding site / kmer
# for a given motif in order for that motif to be considered (for a given window)
MAE_min_motif_fraction: 0.8

# minimal expression of all transcripts supporting an
# alternatively spliced exon (in all samples)
MAE_min_expression: 1.0

# boolean flag to mark TPM expression averaging over samples
MAE_average_expressions: False

# sorting startegy for the output table with motif activities;
# options: "avg" OR "max"
MAE_sorting_strategy: "avg"

...
