__default__:
  time: "00:01:00"
  mem: "1000"
  error: "{params.LOG_cluster_log}"
  output: "/dev/null"

PQA_create_genome_index:
  time: "02:00:00"
  mem: "8000"
  pe: "mpi 8"

PQA_prepare_adapters_textfiles:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PQA_run_FastQC:
  time: "01:00:00"
  mem: "4000"
  pe: "mpi 4"

PQA_remove_adapters_pe:
  time: "02:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_remove_adapters_se:
  time: "02:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_remove_polyA_polyT_tails_pe:
  time: "02:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_remove_polyA_polyT_tails_se:
  time: "02:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_align_reads:
  time: "04:00:00"
  mem: "8000"
  pe: "mpi 8"

PQA_sort_aligned_reads:
  time: "01:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_index_aligned_reads:
  time: "01:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_collapse_genomic_annotation:
  time: "00:10:00"
  mem: "10000"
  pe: "mpi 1"

PQA_mapping_quality_analysis:
  time: "01:00:00"
  mem: "20000"
  pe: "mpi 1"

PQA_merge_mapping_quality_tables:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PQA_extract_transcripts_as_bed12:
  time: "01:00:00"
  mem: "10000"
  pe: "mpi 1"

PQA_calculate_TIN_scores:
  time: "02:00:00"
  mem: "4000"
  pe: "mpi 8"

PQA_merge_TIN_scores:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PQA_calculate_median_TIN_score:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PQA_filter_design_table:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

ASE_build_genome_index:
  time: "00:30:00"
  mem: "20000"
  pe: "mpi 1"

ASE_generate_skipped_exon_events:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"

ASE_filter_events:
  time: "00:30:00"
  mem: "10000"
  pe: "mpi 1"

ASE_cluster_events:
  time: "04:00:00"
  mem: "20000"
  pe: "mpi 1"

ASE_select_representative_events:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

ASE_format_events_into_bed:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

ASE_extract_splice_sites_coordinates:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

TPA_select_tandem_pas:
  time: "02:00:00"
  mem: "5000"
  pe: "mpi 1"

TPA_select_terminal_exon_pas:
  time: "00:10:00"
  mem: "1000"
  pe: "mpi 1"

TPA_filter_on_ambiguous_annotation:
  time: "04:00:00"
  mem: "20000"
  pe: "mpi 1"

TPA_extract_representative_sites_coord:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

QEI_extract_transcriptome:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"

QEI_quantify_expression:
  time: "02:00:00"
  mem: "2000"
  pe: "mpi 8"

QEI_merge_expression_values:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

QEI_filter_expression_tables:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

QEI_calculate_exon_inclusion_scores:
  time: "00:30:00"
  mem: "1000"
  pe: "mpi 1"

PAQ_create_coverages:
  time: "04:00:00"
  mem: "4000"
  pe: "mpi 8"

PAQ_infer_relative_usage:
  time: "04:00:00"
  mem: "4000"
  pe: "mpi 8"

PAQ_relative_pas_positions:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PAQ_normalize_expression:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

PAQ_filter_on_expression:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

CSM_extract_window_coord_and_sequence:
  time: "00:30:00"
  mem: "5000"
  pe: "mpi 1"

CSM_create_kmer_sitecount_matrices:
  time: "01:00:00"
  mem: "5000"
  pe: "mpi 1"

CSM_prepare_MotEvo_parameters:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

CSM_prepare_sequences_for_MotEvo:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

CSM_MotEvo_analysis:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

CSM_create_MotEvo_sitecount_matrices:
  time: "00:30:00"
  mem: "5000"
  pe: "mpi 1"

CSM_create_links_to_matrices:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

MAE_prepare_inclusion_table:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

MAE_fit_model_parameters:
  time: "06:00:00"
  mem: "20000"
  pe: "mpi 1"

MAE_calculate_Zscores:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

MAE_extend_result_tables:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

MAE_calculate_Zscores_statistical_significancy:
  time: "00:30:00"
  mem: "5000"
  pe: "mpi 1"

MAE_collapse_results_for_region:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

KPC_create_polyA_site_to_exon_mapping:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

KPC_tag_overlapping_polyA_sites:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

KPC_select_pas_expression_columns:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

KPC_run_KAPAC_model:
  time: "06:00:00"
  mem: "50000"
  pe: "mpi 1"

KPC_extend_result_tables:
  time: "00:05:00"
  mem: "1000"
  pe: "mpi 1"

KPC_calculate_Zscores_statistical_significancy:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

KPC_collapse_results:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

RES_annotate_statistical_significance:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

RES_select_motifs:
  time: "00:05:00"
  mem: "5000"
  pe: "mpi 1"

RES_prepare_Zscores_tables:
  time: "00:30:00"
  mem: "5000"
  pe: "mpi 1"

RES_plot_Zscores_heatmaps:
  time: "04:00:00"
  mem: "20000"
  pe: "mpi 1"

MAPP_collect_summary:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"

MAPP_prepare_summary_table:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"

MAPP_generate_report:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"

MAPP_summary_tarball:
  time: "00:10:00"
  mem: "5000"
  pe: "mpi 1"
