###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 11-11-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# path to the directory with all the scripts for this pipeline
# (relative to the 'execution' directory)
PQA_scripts_dir: "/home/runner/work/MAPP/MAPP/modules/PREPROCESSING/scripts"

# path for the output directory
# (relative to the 'execution' directory)
PQA_outdir: "/home/runner/work/MAPP/MAPP/modules/PREPROCESSING/output"

# path to the text file with known common adapters sequences
# (relative to the 'execution' directory)
PQA_adapters_sequences: "/home/runner/work/MAPP/MAPP/modules/PREPROCESSING/resources/adapters.txt"

# path to the genomic sequence in fasta format
PQA_genomic_sequence: "/home/runner/work/MAPP/MAPP/.test/integration/module_PQA/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

# path to the genomic annotation in GTF format
PQA_genomic_annotation: "/home/runner/work/MAPP/MAPP/.test/integration/module_PQA/Homo_sapiens.GRCh38.102.gtf"

# TSV-formatted design table with information regarding RNA-Seq samples
PQA_design_file: "/home/runner/work/MAPP/MAPP/.test/integration/module_PQA/design_table.tsv"

# path to (for) the STAR-generated genome index
# if the index does not exists yet - it will be generated in that directory
# note: do not put it under the PQA_outdir!
PQA_index: "/home/runner/work/MAPP/MAPP/modules/PREPROCESSING/index"

# STAR option during the mapping process: --sjdbOverhang
# optimally, it should be set to read length - 1
PQA_sjdbOverhang: 100

# biotype of transcripts included in the TIN score calculation 
PQA_transcript_biotypes: "protein_coding"

# quality filtering cutoffs:
PQA_min_median_TIN_score: 0.0
PQA_RNASeQC_min_mapping_rate: 0.9
PQA_RNASeQC_min_unique_rate_of_mapped: 0.8
PQA_RNASeQC_min_high_quality_rate: 0.2
PQA_RNASeQC_max_intergenic_rate: 0.8
PQA_RNASeQC_max_rRNA_rate: 0.8

# boolean flag: whether to unzip trimmed reads before STAR mapping or not
PQA_storage_efficient: False

...