###############################################################################
#
#   Config options for the snakemake pipeline
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 24-03-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

# path to the directory with all the scripts for this pipeline
# (relative to the 'execution' directory)
QEI_scripts_dir: "../scripts"

# path for the output directory
# (relative to the 'execution' directory)
QEI_outdir: "../output"

# path to the genomic annotation in GTF format
QEI_genomic_annotation: ""

# path to the genomic sequence in fasta format
# NOTE:
# unfortunately there is no separate gffread flag for a genomic sequence index;
# genome FASTA file should be accompanied by FASTA INDEX (.fai) file
# in the same directory, under the same core name; in case it is not:
# gffread will create the index on-the-fly and save it alongside the genomic sequence
# (thus, the user requires write permission to the directory below in such scenario)
QEI_genomic_sequence: ""

# per-sample paths to the bam files with transcriptomic alignments
QEI_alignment_files:
  "": ""

# TSV-formatted design table with information regarding RNA-Seq samples (quality-filtered set)
QEI_design_table: ""

# TSV table with alternatively spliced exon
# (cluster representatives from ASE module)
QEI_exon_set: ""

...
