###############################################################################
#
#   GitHub Actions CI configuration for integration tests
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 14-12-2021
#   LICENSE: MIT
#
###############################################################################
---

name: integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  MAPP-test1:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout mapp repository
        uses: actions/checkout@v2

      - name: Setup miniconda & mapp main environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: env/environment.yml
          activate-environment: mapp
          auto-activate-base: false

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Create the main configfile
        run: |
          python scripts/create-main-config-file.py \
          --config-template .test/integration/MAPP/config_template_1.yml \
          --pipeline-configfile configs/config.yml

...
