###############################################################################
#
#   GitHub Actions CI configuration for integration tests
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 14-12-2021
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  MAE-module:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout mapp repository
        uses: actions/checkout@v2

      - name: Setup miniconda & mapp main environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: env/environment.yml
          activate-environment: mapp
          auto-activate-base: false

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Create snakemake DAG
        run: |
          bash modules/MAEI/execution/run.sh \
          -c .test/integration/module_MAE/config.yml \
          -e local \
          -t conda \
          -g dag dag.svg

      - name: Initiate snakemake dry run
        run: |
          snakemake \
          --snakefile=modules/MAEI/Snakefile \
          --configfile=.test/integration/module_MAE/config.yml \
          --printshellcmds \
          --dryrun \
          --verbose

      - name: Build conda envs for all the rules
        run: |
          snakemake \
          --snakefile=modules/MAEI/Snakefile \
          --configfile=.test/integration/module_MAE/config.yml \
          --use-conda \
          --conda-create-envs-only \
          --cores 8

...
