###############################################################################
#
#   GitHub Actions CI configuration for integration tests
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 14-12-2021
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  MAPP-test2:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout mapp repository
        uses: actions/checkout@v2

      - name: Setup miniconda & mapp main environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: env/environment.yml
          activate-environment: mapp
          auto-activate-base: false

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Download genomic resources
        run: |
          bash scripts/download-ENSEMBL-resources.sh \
          --species hsa \
          --output-directory resources_ENSEMBL_hsa

      - name: Download the atlas of PolyA sites
        run: |
          bash scripts/download-polyA-atlas.sh \
          --species hsa \
          --output-directory ATLAS2_hsa

      - name: Download and parse ATtRACT motifs
        run: |
          bash scripts/download-and-parse-ATtRACT-motifs.sh \
          --output-directory ATtRACT_hsa

      # for this test it is required that we set the
      # modification date of resources files as older than
      # the pipeline files (expected situation):
      - name: Adjust modification date for resources
        run: |
          touch -a -m -t 200001010000.00 resources_ENSEMBL_hsa/Homo_sapiens.GRCh38.102.gtf
          touch -a -m -t 200001010000.00 resources_ENSEMBL_hsa/Homo_sapiens.GRCh38.dna.primary_assembly.fa
          touch -a -m -t 200001010000.00 ATLAS2_hsa/reformatted_filtered_atlas.bed

      # according to the notes in the pipeline configuration:
      # comment-out ASE, TPA and CSM modules inclusion from the main Snakefile:
      - name: Comment-out ASE, TPA, CSM modules
        run: |
          sed '52 {s/^/#/}' -i Snakefile
          sed '53 {s/^/#/}' -i Snakefile
          sed '56 {s/^/#/}' -i Snakefile

      - name: Create the main configfile
        run: |
          python scripts/create-main-config-file.py \
          --config-template .test/integration/MAPP/config_template_2.yml \
          --pipeline-configfile configs/config.yml

      - name: Create snakemake rulegraph
        run: |
          bash execution/run.sh \
          -c configs/config.yml \
          -e local \
          -t conda \
          -g rulegraph rulegraph.svg

      - name: Create snakemake DAG
        run: |
          bash execution/run.sh \
          -c configs/config.yml \
          -e local \
          -t conda \
          -g dag dag.svg

      - name: Initiate snakemake dry run
        run: |
          snakemake \
          --snakefile=Snakefile \
          --configfile=configs/config.yml \
          --printshellcmds \
          --dryrun \
          --verbose

...
