name: integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  MAPP-test1:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout mapp repository
        uses: actions/checkout@v2

      - name: Setup miniconda & mapp main environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          environment-file: env/environment.yml
          activate-environment: mapp
          auto-activate-base: false

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      #- name: Run test script for snakemake DAG
      #  run: bash tests/test_create_dag_image/test.sh
